### ISSUE TITLE
[Bug] Looking up git refs fails.

### ISSUE THREAD

**Issue by andrewcrook** [asdf-community/asdf-plugin-manager#32]
**Describe the bug**

All the git refs fail and cannot be found. These were all install fresh today

**Steps to reproduce**

```
asdf plugin add XXX
asdf-plugin-manager export > .plugin-versions 
asdf-plugin-manager add-all
```

**Expected behavior**

To check all the git refs

**Screenshots**
**Additional context**

```
> asdf-plugin-manager list
asdf-plugin-manager  https://github.com/asdf-community/asdf-plugin-manager.git  07a8a5a
direnv               https://github.com/asdf-community/asdf-direnv.git          2b649c8
lua                  https://github.com/Stratus3D/asdf-lua.git                  36fae6e
luajit               https://github.com/smashedtoatoms/asdf-luaJIT.git          bbfe3cd
python               https://github.com/danhper/asdf-python.git                 5e277e2
```

```
> asdf-plugin-manager add-all
[INFO] Adding: asdf-plugin-manager https://github.com/asdf-community/asdf-plugin-manager.git 07a8a5a
Plugin named asdf-plugin-manager already added
Location of asdf-plugin-manager plugin: /Users/XXXXX/.local/share/asdf/plugins/asdf-plugin-manager
Updating asdf-plugin-manager to 07a8a5a
fatal: couldn't find remote ref 07a8a5a
HEAD is now at 07a8a5a chore(deps): bump asdf-vm/actions from 2 to 3 (#30)
[INFO] Done.
[INFO] Adding: direnv https://github.com/asdf-community/asdf-direnv.git 2b649c8
Plugin named direnv already added
Location of direnv plugin: /Users/XXXXX/.local/share/asdf/plugins/direnv
Updating direnv to 2b649c8
fatal: couldn't find remote ref 2b649c8
HEAD is now at 2b649c8 Bump asdf-vm/actions from 2 to 3
[INFO] Done.
[INFO] Adding: lua https://github.com/Stratus3D/asdf-lua.git 36fae6e
Plugin named lua already added
Location of lua plugin: /Users/XXXXX/.local/share/asdf/plugins/lua
Updating lua to 36fae6e
fatal: couldn't find remote ref 36fae6e
HEAD is now at 36fae6e Add Lua 5.4.5 and 5.4.6 (#32)
[INFO] Done.
[INFO] Adding: luajit https://github.com/smashedtoatoms/asdf-luaJIT.git bbfe3cd
Plugin named luajit already added
Location of luajit plugin: /Users/XXXXX/.local/share/asdf/plugins/luajit
Updating luajit to bbfe3cd
fatal: couldn't find remote ref bbfe3cd
HEAD is now at bbfe3cd Attempting to fix missing luarocks.cfg
[INFO] Done.
[INFO] Adding: python https://github.com/danhper/asdf-python.git 5e277e2
Plugin named python already added
Location of python plugin: /Users/XXXXX/.local/share/asdf/plugins/python
Updating python to 5e277e2
fatal: couldn't find remote ref 5e277e2
HEAD is now at 5e277e2 Merge pull request #169 from asdf-community/renovate/configure
[INFO] Done.
```

**Comment by timdp** [comment]
This appears to be because these are short refs (generally 7 characters) and Git won't resolve those. I wonder how it ever worked. Is it a regression in asdf?

Some initial digging: `asdf-plugin-manager export` calls `asdf plugin-list --refs`, which in turn calls the internal function `get_plugin_remote_gitref`, which is basically `git rev-parse --short`. The `--short` argument isn't configurable.

**Comment by andrewcrook** [comment]
@timdp 

I did manage to get export to use the full git ref, however, there is an issue with `asdf update` itself 
So I closed the pull request.

`asdf update` does  something like this 

`git fetch --prune --update-head-ok origin daa7d6ee57:daa7d6ee57`

and will not find the repo/commit based on the short git ref.

I think something like the following is required 

`git fetch --prune --update-head-ok origin  daa7d6ee570117f893b7f3a8ae034a722d641a6a:daa7d6ee57`

```
 > git --git-dir .git rev-parse HEAD
daa7d6ee570117f893b7f3a8ae034a722d641a6a

> git branch
* (HEAD detached at daa7d6e)
  master
```

I will raise something with the asdf team

**Comment by timdp** [comment]
Assuming everything's a Git ref, you could probably also bypass asdf entirely and run `git fetch` and `git log` (with the appropriate flags) in the local tool repo yourself? Seems invasive though.

**Comment by aabouzaid** [comment]
Hi @andrewcrook :wave: 
Which `asdf` and `asdf-plugin-manager` version do you have?

**Comment by timdp** [comment]
Any updates here?

I think one option would be to add a `git rev-parse` call to expand/normalize hashes before passing them to asdf. That would require an API to resolve a plugin name to the git repo path though, which I don't think asdf exposes, so maybe it's just shifting the problem.

As a sidenote, shouldn't the fatal error make asdf-plugin-manager crash out?

**Comment by aabouzaid** [comment]
I've released v1.2.0, it should fix that issue which actually coming from asdf update itself.

I used the same idea proposed by @timdp to checkout the git hash.

Could you please give it a try?

```
asdf install asdf-plugin-manager 1.2.0
```

**Comment by timdp** [comment]
Working great here! 👍🏻

**Comment by aabouzaid** [comment]
@timdp thanks for the confirmation :handshake:
