### ISSUE TITLE
When running `update-all` up to date plugins crash the process

### ISSUE THREAD

**Issue by ivuorinen** [asdf-community/asdf-plugin-manager#62]
**Describe the bug**

Looks like https://github.com/asdf-community/asdf-plugin-manager/issues/38 has made a comeback, partly at least.

Running `asdf-plugin-manager update-all` script starts to update the plugin repos, but when encountering up to date repository sed gives an error.
Running the command again seems to restart the process and continue updating the plugins.

```shell
[...]
[INFO] The plugin "python" with git-ref "7b0af87" is already up-to-date.
[INFO] Updating: ripgrep https://gitlab.com/wt0f/asdf-ripgrep.git e836665 to HEAD
Location of ripgrep plugin: [home]/.local/bin/asdf/plugins/ripgrep
Updating ripgrep to master
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
[INFO] The plugin "ripgrep" with git-ref "e836665" is already up-to-date.
[INFO] Updating: ruby https://github.com/asdf-vm/asdf-ruby.git 27f78c9 to HEAD
Location of ruby plugin: [home]/.local/bin/asdf/plugins/ruby
Updating ruby to master
From https://github.com/asdf-vm/asdf-ruby
   d6eb414..96334db  master     -> master
   d6eb414..96334db  master     -> origin/master
Previous HEAD position was 27f78c9 Update utils.sh (#407)
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
[INFO] Updating git-ref in plugin version file: [home]/.config/asdf/plugin-versions
sed: 1: "[home]/.confi ...": command i expects \ followed by text
```

**Steps to reproduce**

Have some plugins out of date, one up to date.

**Expected behavior**

Script skips the plugin repos that are up to date without crashing.

**Additional context**

I'm running latest `asdf` on latest macOS (14.6.1) in zsh, and latest `asdf-plugin-manager`.

```shell
$ asdf version
v0.14.1

$ asdf-plugin-manager version
1.3.1

$ asdf-plugin-manager update asdf-plugin-manager
[INFO] Updating: asdf-plugin-manager https://github.com/asdf-community/asdf-plugin-manager.git ecd1642 to HEAD
Location of asdf-plugin-manager plugin: [home]/.local/bin/asdf/plugins/asdf-plugin-manager
Updating asdf-plugin-manager to main
Already on 'main'
Your branch is up to date with 'origin/main'.
[INFO] The plugin "asdf-plugin-manager" with git-ref "ecd1642" is already up-to-date.

$ asdf-plugin-manager list | grep plugin-manager
asdf-plugin-manager   https://github.com/asdf-community/asdf-plugin-manager.git            ecd1642
```

Link to the commit for easier access: https://github.com/asdf-community/asdf-plugin-manager/commit/ecd1642

**Comment by ivuorinen** [comment]
Shouldn't the latest commit `asdf-plugin-manager` updates to be https://github.com/asdf-community/asdf-plugin-manager/commit/54ac3421d8eea32dd03e3a708e5188cd3489137f which corresponds to https://github.com/asdf-community/asdf-plugin-manager/releases/tag/v1.3.1 ?

**Comment by aabouzaid** [comment]
I believe that's because the sed used in MacOS is BSD sed which uses some different syntax.

This should be an easy fix for it so no need to relay on sed to edit the file directly.

```
cat "$(print_plugin_versions_filename)" | sed "/^\b${plugin_name}\b/ s/${plugin_ref_managed}/${plugin_ref_after_update}/" |
    tee "$(print_plugin_versions_filename)"
```

**Comment by aabouzaid** [comment]
I will test that and make a fix.

**Comment by aabouzaid** [comment]
I've fixed the issue, which will be included in the next release.

**Comment by ivuorinen** [comment]
Awesome, thank you! Will report back.

**Comment by ivuorinen** [comment]
Confirming the fix now lets you update all plugins without problems 🎉
